workspace:
  base: /go
  path: src/github.com/UKHomeOffice/policy-admission

pipeline:
  tests:
    image: golang:1.13.10
    commands:
      - make test
      - make static
    when:
      event: [push, tag]

  build-image:
    image: docker:17.09.0-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t policy-admission:$${DRONE_COMMIT_SHA} .
    when:
      event: [push, tag]

  scan-image:
    image: quay.io/ukhomeofficedigital/anchore-submission:latest
    image_name: policy-admission:${DRONE_COMMIT_SHA}
    when:
      event: [push, tag]

  latest:
    image: docker:17.09.0-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets: [docker_password]
    commands:
      - docker tag policy-admission:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/policy-admission:latest
      - docker login -u="ukhomeofficedigital+policy_admission" -p=$${DOCKER_PASSWORD} quay.io
      - docker push quay.io/ukhomeofficedigital/policy-admission:latest
    when:
      event: push
      branch: master

  tagged:
    image: docker:17.09.0-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets: [docker_password]
    commands:
      - docker tag policy-admission:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/policy-admission:$${DRONE_TAG}
      - docker login -u="ukhomeofficedigital+policy_admission" -p=$${DOCKER_PASSWORD} quay.io
      - docker push quay.io/ukhomeofficedigital/policy-admission:$${DRONE_TAG}
    when:
      event: tag
