---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

workspace:
  path: /go/src/github.com/UKHomeOffice/policy-admission

steps:
- name: tests
  image: golang:1.17.3
  commands:
  - make test
  - make static
  when:
    event:
    - push
    - tag
    - pull_request

- name: build-image
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  # wait for docker service to be up before running docker build
  - n=0; while [ "$n" -lt 60 ] && [ ! "$(docker stats --no-stream)" ]; do n=$(( n + 1 )); sleep 1; done
  - docker build -t policy-admission:$${DRONE_COMMIT_SHA} .
  when:
    event:
    - push
    - tag
    - pull_request

- name: scan-image
  pull: Always
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
  resources:
    limits:
      cpu: 1000
      memory: 1024Mi
  environment:
    IMAGE_NAME: policy-admission:${DRONE_COMMIT_SHA}
    IGNORE_UNFIXED: "true"
  when:
    event:
    - pull_request
    - push
    - tag

- name: latest
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - docker tag policy-admission:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/policy-admission:latest
  - docker login -u="ukhomeofficedigital+policy_admission" -p=$${DOCKER_PASSWORD} quay.io
  - docker push quay.io/ukhomeofficedigital/policy-admission:latest
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
    branch:
    - main
    event:
    - push

- name: tagged
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - docker tag policy-admission:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/policy-admission:$${DRONE_TAG}
  - docker login -u="ukhomeofficedigital+policy_admission" -p=$${DOCKER_PASSWORD} quay.io
  - docker push quay.io/ukhomeofficedigital/policy-admission:$${DRONE_TAG}
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
    event:
    - tag

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
