---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: policy-admission.acp.homeoffice.gov.uk
webhooks:
- name: policy-admission.acp.homeoffice.gov.uk
  failurePolicy: Ignore
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - "*"
    apiVersions:
    - "*"
    resources:
    - deployments
    - ingresses
    - pods
    - services
  clientConfig:
    service:
      namespace: kube-admission
      name: policy-admission
    caBundle: ${CA_BUNDLE}
